# fly.toml app configuration file generated for crm-inmobiliario on 2026-06-01T14:31:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crm-inmobiliario'
primary_region = 'cdg'

[build]

[env]
  APP_URL = 'https://crm-inmobiliario.fly.dev'
  NODE_ENV = 'production'
  PORT = '3002'
  VITE_API_URL = '/api'

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/api/health"
    timeout = "5s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
